apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-sa
  namespace: testcode-namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::707677861059:role/SecretsManagerIRSAReadRole
