apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: redis
spec:
  serviceName: redis
  replicas: 3                        # Redis Pod 3개 생성 (각 파드마다 전용 EBS 볼륨 부착됨)
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data      # Redis 데이터 저장 경로

          # 로그 파일 설정
          args:
            - "--logfile"           # 로그 출력 설정
            - ""                    ### 로그 파일 대신 stdout(표준 출력)으로 출력
            - "--appendonly"        # Redis의 AOF(Append Only File) 지속성 모드 설정
            - "yes"                 ### AOF 활성화 (선택사항) ⇒ 모든 쓰기 작업을 로그 파일에 기록
            
  volumeClaimTemplates:             # 볼륨 직접 연결하는게 아니라 PVC로 연결함
    - metadata:
        name: redis-storage
      spec:
        storageClassName: redis-sc  # 위에서 만든 StorageClass 사용
        accessModes:
          - ReadWriteOnce           # EBS는 한 Pod에서만 사용 가능
        resources:
          requests:
            storage: 3Gi            # 원하는 스토리지 크기
