apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: redis
spec:
  selector:
    app: redis  # Redis StatefulSet의 라벨과 일치해야 함
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
